<?php

namespace Database\Seeders;

use App\Models\Address;
use App\Models\Author;
use App\Models\Banner;
use App\Models\Blog;
use App\Models\BlogCategory;
use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class EcommerceSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Default Demo User & Store Administrator
        $user = User::firstOrCreate(
            ['email' => 'test@example.com'],
            [
                'name' => 'John Doe',
                'password' => Hash::make('password123'),
                'role' => 'customer',
                'phone' => '+1234567890',
            ]
        );

        $admin = User::firstOrCreate(
            ['email' => 'admin@ecommerce.com'],
            [
                'name' => 'Store Administrator',
                'password' => Hash::make('password123'),
                'role' => 'admin',
                'phone' => '+1987654321',
            ]
        );

        // 2. Categories
        $categories = [
            [
                '_id' => 'cat-1',
                'title' => 'Gadgets & Audio',
                'name' => 'Gadgets & Audio',
                'slug' => 'gadget-accessories',
                'description' => 'Premium headphones, earbuds, and audio accessories.',
                'productCount' => 14,
                'image' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'cat-2',
                'title' => 'Smartphones',
                'name' => 'Smartphones',
                'slug' => 'smartphones',
                'description' => 'Next-gen flagship smartphones and accessories.',
                'productCount' => 18,
                'image' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'cat-3',
                'title' => 'Smart Watches',
                'name' => 'Smart Watches',
                'slug' => 'smart-watches',
                'description' => 'Fitness trackers, cellular smartwatches, and bands.',
                'productCount' => 12,
                'image' => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'cat-4',
                'title' => 'Appliances',
                'name' => 'Appliances',
                'slug' => 'appliances',
                'description' => 'Smart home electronics and intelligent appliances.',
                'productCount' => 9,
                'image' => 'https://images.unsplash.com/photo-1588854337221-4cf9fa96059c?w=800&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'cat-5',
                'title' => 'Laptops & Computers',
                'name' => 'Laptops & Computers',
                'slug' => 'laptops',
                'description' => 'High-performance ultrabooks and workstation gear.',
                'productCount' => 16,
                'image' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'cat-6',
                'title' => 'Gaming & VR',
                'name' => 'Gaming & VR',
                'slug' => 'gaming',
                'description' => 'Controllers, headsets, mechanical keyboards, and displays.',
                'productCount' => 11,
                'image' => 'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=800&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'cat-7',
                'title' => 'Cameras & Drones',
                'name' => 'Cameras & Drones',
                'slug' => 'cameras-drones',
                'description' => 'Mirrorless cameras, 4K action cams, cinematic gimbals, and aerial drones.',
                'productCount' => 8,
                'image' => 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'cat-8',
                'title' => 'Smart Home & Security',
                'name' => 'Smart Home & Security',
                'slug' => 'smart-home-security',
                'description' => 'Smart locks, video doorbells, ambient lighting, and automated hubs.',
                'productCount' => 10,
                'image' => 'https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'cat-9',
                'title' => 'Monitors & Displays',
                'name' => 'Monitors & Displays',
                'slug' => 'monitors-displays',
                'description' => 'OLED curved gaming monitors, 4K creator panels, and ultra-wide screens.',
                'productCount' => 9,
                'image' => 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'cat-10',
                'title' => 'Tablets & E-Readers',
                'name' => 'Tablets & E-Readers',
                'slug' => 'tablets-ereaders',
                'description' => 'Pro drawing tablets, featherweight e-readers, and high-res stylus displays.',
                'productCount' => 7,
                'image' => 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'cat-11',
                'title' => 'PC Components & Hardware',
                'name' => 'PC Components & Hardware',
                'slug' => 'pc-components',
                'description' => 'Flagship graphics cards, processors, motherboards, liquid cooling, and ultra-speed RAM.',
                'productCount' => 14,
                'image' => 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'cat-12',
                'title' => 'Studio Audio & Soundbars',
                'name' => 'Studio Audio & Soundbars',
                'slug' => 'audio-speakers',
                'description' => 'Dolby Atmos cinematic soundbars, studio monitors, and acoustic home speakers.',
                'productCount' => 12,
                'image' => 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'cat-13',
                'title' => 'Smart Health & Wellness',
                'name' => 'Smart Health & Wellness',
                'slug' => 'smart-health',
                'description' => 'Percussive therapy massagers, body composition analyzers, and restorative therapy gear.',
                'productCount' => 10,
                'image' => 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'cat-14',
                'title' => 'Networking & Smart Wi-Fi',
                'name' => 'Networking & Smart Wi-Fi',
                'slug' => 'networking-wifi',
                'description' => 'Next-gen Wi-Fi 7 mesh systems, tri-band gaming routers, and high-speed gigabit switches.',
                'productCount' => 8,
                'image' => 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'cat-15',
                'title' => 'Power & Solar Energy',
                'name' => 'Power & Solar Energy',
                'slug' => 'power-charging',
                'description' => 'High-capacity GaN power stations, portable solar arrays, and ultra-fast charging accessories.',
                'productCount' => 11,
                'image' => 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=800&auto=format&fit=crop&q=80',
            ],
        ];

        $categoryModels = [];
        foreach ($categories as $cat) {
            $categoryModels[$cat['slug']] = Category::updateOrCreate(['slug' => $cat['slug']], $cat);
        }

        // 3. Brands
        $brands = [
            [
                '_id' => 'brand-1',
                'title' => 'Apple',
                'name' => 'Apple',
                'brandName' => 'Apple',
                'slug' => 'apple',
                'image' => 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=400&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'brand-2',
                'title' => 'Sony',
                'name' => 'Sony',
                'brandName' => 'Sony',
                'slug' => 'sony',
                'image' => 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'brand-3',
                'title' => 'Samsung',
                'name' => 'Samsung',
                'brandName' => 'Samsung',
                'slug' => 'samsung',
                'image' => 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'brand-4',
                'title' => 'Bose',
                'name' => 'Bose',
                'brandName' => 'Bose',
                'slug' => 'bose',
                'image' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'brand-5',
                'title' => 'DJI',
                'name' => 'DJI',
                'brandName' => 'DJI',
                'slug' => 'dji',
                'image' => 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=400&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'brand-6',
                'title' => 'ASUS ROG',
                'name' => 'ASUS ROG',
                'brandName' => 'ASUS ROG',
                'slug' => 'asus-rog',
                'image' => 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=400&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'brand-7',
                'title' => 'Logitech',
                'name' => 'Logitech',
                'brandName' => 'Logitech',
                'slug' => 'logitech',
                'image' => 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=400&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'brand-8',
                'title' => 'Canon',
                'name' => 'Canon',
                'brandName' => 'Canon',
                'slug' => 'canon',
                'image' => 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'brand-9',
                'title' => 'Google',
                'name' => 'Google',
                'brandName' => 'Google',
                'slug' => 'google',
                'image' => 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'brand-10',
                'title' => 'LG',
                'name' => 'LG',
                'brandName' => 'LG',
                'slug' => 'lg',
                'image' => 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'brand-11',
                'title' => 'Microsoft',
                'name' => 'Microsoft',
                'brandName' => 'Microsoft',
                'slug' => 'microsoft',
                'image' => 'https://images.unsplash.com/photo-1633419461186-7d40a38105ec?w=400&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'brand-12',
                'title' => 'Razer',
                'name' => 'Razer',
                'brandName' => 'Razer',
                'slug' => 'razer',
                'image' => 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'brand-13',
                'title' => 'Marshall',
                'name' => 'Marshall',
                'brandName' => 'Marshall',
                'slug' => 'marshall',
                'image' => 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=400&auto=format&fit=crop&q=80',
            ],
        ];

        $brandModels = [];
        foreach ($brands as $b) {
            $brandModels[$b['slug']] = Brand::updateOrCreate(['slug' => $b['slug']], $b);
        }

        // 4. Banners
        $banners = [
            [
                '_id' => 'banner-1',
                'title' => 'Spatial Audio Revolution',
                'subtitle' => 'AirPods Max & Pro Series',
                'description' => 'Experience active noise cancellation and computational spatial sound with zero distortion.',
                'badge' => 'New Year Special',
                'discountAmount' => 20,
                'link' => '/product/airpods-max-space-gray',
                'image' => 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=1920&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'banner-2',
                'title' => 'Titanium Masterpiece',
                'subtitle' => 'iPhone 16 Pro Max 512GB',
                'description' => 'Equipped with the A18 Pro silicon chip, 48MP Fusion camera system, and ultra-durable grade-5 titanium.',
                'badge' => 'Hot Release',
                'discountAmount' => 10,
                'link' => '/product/iphone-16-pro-max-natural-titanium',
                'image' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1920&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'banner-3',
                'title' => 'Next-Gen Smart Living',
                'subtitle' => 'Intelligent Climate & Home Hub',
                'description' => 'Automate ambient temperature, humidity, and air purification with Matter-enabled voice assistant sync.',
                'badge' => 'Featured Deal',
                'discountAmount' => 15,
                'link' => '/product/dyson-purifier-hot-cool',
                'image' => 'https://images.unsplash.com/photo-1588854337221-4cf9fa96059c?w=1920&auto=format&fit=crop&q=80',
            ],
            [
                '_id' => 'banner-4',
                'title' => 'Pure Gaming Dominance',
                'subtitle' => 'Razer Blade 16 & RTX 4090 Series',
                'description' => 'Experience blisteringly fast dual-mode Mini-LED display, Intel Core i9-14900HX, and unmatched vapor chamber cooling.',
                'badge' => 'Ultimate Performance',
                'discountAmount' => 12,
                'link' => '/product/razer-blade-16-gaming-laptop',
                'image' => 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=1920&auto=format&fit=crop&q=80',
            ],
        ];

        foreach ($banners as $ban) {
            Banner::updateOrCreate(['_id' => $ban['_id']], $ban);
        }

        // 5. Products
        $products = [
            [
                '_id' => 'prod-1',
                'name' => 'Sony WH-1000XM5 Wireless Headphones',
                'slug' => 'sony-wh-1000xm5-wireless-headphones',
                'price' => 399.99,
                'discount' => 15,
                'stock' => 18,
                'status' => 'hot',
                'variant' => 'gadget',
                'isFeatured' => true,
                'brand_id' => $brandModels['sony']->id,
                'category_slug' => 'gadget-accessories',
                'images' => [
                    'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'Industry-leading noise cancellation with two processors and 8 microphones. Up to 30-hour battery life with quick charging.',
                'description' => '<p>The Sony WH-1000XM5 headphones rewrite the rules for distraction-free listening. Two processors control 8 microphones for unprecedented noise cancellation and exceptional call quality.</p>',
            ],
            [
                '_id' => 'prod-2',
                'name' => 'iPhone 16 Pro Max Natural Titanium',
                'slug' => 'iphone-16-pro-max-natural-titanium',
                'price' => 1199.00,
                'discount' => 5,
                'stock' => 24,
                'status' => 'new',
                'variant' => 'smartphones',
                'isFeatured' => true,
                'brand_id' => $brandModels['apple']->id,
                'category_slug' => 'smartphones',
                'images' => [
                    'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'Grade 5 Titanium frame with ceramic shield front. Powered by Apple A18 Pro 3nm chipset with dedicated Camera Control slider.',
                'description' => '<p>The iPhone 16 Pro Max features a stunning strong and lightweight titanium design with larger 6.9-inch Super Retina XDR display.</p>',
            ],
            [
                '_id' => 'prod-3',
                'name' => 'MacBook Pro 16" M4 Max',
                'slug' => 'macbook-pro-16-m4-max',
                'price' => 3499.00,
                'discount' => 8,
                'stock' => 9,
                'status' => 'hot',
                'variant' => 'laptops',
                'isFeatured' => true,
                'brand_id' => $brandModels['apple']->id,
                'category_slug' => 'laptops',
                'images' => [
                    'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => '16-core CPU, 40-core GPU, 48GB unified memory. Liquid Retina XDR display with nano-texture option.',
                'description' => '<p>MacBook Pro delivers unprecedented pro performance with the cutting-edge M4 Max chip, stunning Liquid Retina XDR display, and up to 24 hours of battery life.</p>',
            ],
            [
                '_id' => 'prod-4',
                'name' => 'Samsung Galaxy S25 Ultra 512GB',
                'slug' => 'samsung-galaxy-s25-ultra',
                'price' => 1299.99,
                'discount' => 12,
                'stock' => 15,
                'status' => 'sale',
                'variant' => 'smartphones',
                'isFeatured' => true,
                'brand_id' => $brandModels['samsung']->id,
                'category_slug' => 'smartphones',
                'images' => [
                    'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'Snapdragon 8 Elite for Galaxy, 200MP Quad Telephoto Camera, integrated S-Pen, and Galaxy AI 2.0 suites.',
                'description' => '<p>Samsung Galaxy S25 Ultra brings transformative productivity and mobile photography with built-in Galaxy AI and titanium body.</p>',
            ],
            [
                '_id' => 'prod-5',
                'name' => 'Apple Watch Ultra 2 Titanium GPS + Cellular',
                'slug' => 'apple-watch-ultra-2',
                'price' => 799.00,
                'discount' => 0,
                'stock' => 11,
                'status' => 'new',
                'variant' => 'smart-watches',
                'isFeatured' => false,
                'brand_id' => $brandModels['apple']->id,
                'category_slug' => 'smart-watches',
                'images' => [
                    'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => '3000 nits brightness display, S9 SiP chip, precision dual-frequency GPS, and up to 72 hours battery in low-power mode.',
                'description' => '<p>The most rugged and capable Apple Watch pushes the boundaries of extreme sports, diving, and endurance endurance tracking.</p>',
            ],
            [
                '_id' => 'prod-6',
                'name' => 'Bose QuietComfort Ultra Spatial Headphones',
                'slug' => 'bose-quietcomfort-ultra',
                'price' => 429.00,
                'discount' => 14,
                'stock' => 7,
                'status' => 'hot',
                'variant' => 'gadget',
                'isFeatured' => true,
                'brand_id' => $brandModels['bose']->id,
                'category_slug' => 'gadget-accessories',
                'images' => [
                    'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'CustomTune acoustic calibration with Bose Immersive Audio spatial rendering. World-class quiet mode.',
                'description' => '<p>High-fidelity audio with breakthrough Bose Immersive Audio for sound that feels real and spacious.</p>',
            ],
            [
                '_id' => 'prod-7',
                'name' => 'DJI Mini 4 Pro Drone Fly More Combo',
                'slug' => 'dji-mini-4-pro-drone-fly-more-combo',
                'price' => 1099.00,
                'discount' => 8,
                'stock' => 12,
                'status' => 'hot',
                'variant' => 'cameras',
                'isFeatured' => true,
                'brand_id' => $brandModels['dji']->id,
                'category_slug' => 'cameras-drones',
                'images' => [
                    'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'Under 249g ultra-lightweight, 4K/60fps HDR True Vertical Shooting, Omnidirectional Obstacle Sensing, 20km FHD Video Transmission.',
                'description' => '<p>Capture complex aerial shots with DJI Mini 4 Pro. Packed with powerful imaging upgrades and omnidirectional active obstacle sensing for effortless cinematic flights.</p>',
            ],
            [
                '_id' => 'prod-8',
                'name' => 'Canon EOS R6 Mark II Mirrorless Camera Body',
                'slug' => 'canon-eos-r6-mark-ii-mirrorless-camera',
                'price' => 2499.00,
                'discount' => 10,
                'stock' => 6,
                'status' => 'new',
                'variant' => 'cameras',
                'isFeatured' => true,
                'brand_id' => $brandModels['canon']->id,
                'category_slug' => 'cameras-drones',
                'images' => [
                    'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => '24.2MP Full-Frame CMOS sensor, 40 fps electronic shutter burst, 4K 60p 10-bit internal video, Dual Pixel CMOS AF II with Deep Learning AI.',
                'description' => '<p>Master both motion and stills with the Canon EOS R6 Mark II. Blistering continuous shooting speed and 6K oversampled 4K 60p video make it the ultimate hybrid creator tool.</p>',
            ],
            [
                '_id' => 'prod-9',
                'name' => 'ASUS ROG Swift OLED PG32UCDM 32" 4K 240Hz Gaming Monitor',
                'slug' => 'asus-rog-swift-oled-pg32ucdm',
                'price' => 1299.99,
                'discount' => 5,
                'stock' => 9,
                'status' => 'hot',
                'variant' => 'monitors',
                'isFeatured' => true,
                'brand_id' => $brandModels['asus-rog']->id,
                'category_slug' => 'monitors-displays',
                'images' => [
                    'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => '32-inch 4K QD-OLED panel, 240Hz refresh rate, 0.03ms GtG response time, custom heatsink with graphene film to prevent burn-in.',
                'description' => '<p>Experience breathtaking visual fidelity and unmatched responsiveness with the ROG Swift OLED PG32UCDM. Next-gen QD-OLED technology delivers inky blacks and infinite contrast.</p>',
            ],
            [
                '_id' => 'prod-10',
                'name' => 'Logitech MX Master 3S Wireless Performance Mouse',
                'slug' => 'logitech-mx-master-3s-wireless-mouse',
                'price' => 99.99,
                'discount' => 15,
                'stock' => 45,
                'status' => 'sale',
                'variant' => 'gadget',
                'isFeatured' => false,
                'brand_id' => $brandModels['logitech']->id,
                'category_slug' => 'gadget-accessories',
                'images' => [
                    'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => '8K DPI any-surface tracking including glass, Quiet Clicks with 90% noise reduction, MagSpeed electromagnetic scrolling up to 1,000 lines/sec.',
                'description' => '<p>Logitech MX Master 3S is an iconic mouse remastered for ultimate tactile feel and whisper-quiet performance on multi-computer desktop setups.</p>',
            ],
            [
                '_id' => 'prod-11',
                'name' => 'Google Pixel 9 Pro Fold Obsidian 256GB',
                'slug' => 'google-pixel-9-pro-fold',
                'price' => 1799.00,
                'discount' => 8,
                'stock' => 11,
                'status' => 'new',
                'variant' => 'smartphones',
                'isFeatured' => true,
                'brand_id' => $brandModels['google']->id,
                'category_slug' => 'smartphones',
                'images' => [
                    'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'Google Tensor G4 chip with Gemini Nano AI, 8-inch Super Actua Flex inner display, fluid aerospace-grade multi-alloy hinge, IPX8 water resistance.',
                'description' => '<p>The thinnest foldable with the largest inner display. Experience Gemini Live, multi-screen multitasking, and revolutionary triple rear camera system.</p>',
            ],
            [
                '_id' => 'prod-12',
                'name' => 'Apple iPad Pro 13-inch M4 Ultra Retina Tandem OLED',
                'slug' => 'apple-ipad-pro-13-inch-m4',
                'price' => 1299.00,
                'discount' => 0,
                'stock' => 14,
                'status' => 'hot',
                'variant' => 'tablets',
                'isFeatured' => true,
                'brand_id' => $brandModels['apple']->id,
                'category_slug' => 'tablets-ereaders',
                'images' => [
                    'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1585790050230-5dd28404ccb9?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'Thinnest Apple product ever at 5.1mm, Ultra Retina XDR Tandem OLED with 1600 nits peak HDR brightness, powerhouse Apple M4 chip with hardware ray tracing.',
                'description' => '<p>iPad Pro introduces groundbreaking Tandem OLED display technology and the mind-blowing Apple M4 silicon chip, revolutionizing portable computing and digital art workflows.</p>',
            ],
            [
                '_id' => 'prod-13',
                'name' => 'LG C4 Series 65-inch 4K Smart OLED evo TV',
                'slug' => 'lg-c4-series-65-inch-4k-oled-evo-tv',
                'price' => 1999.99,
                'discount' => 20,
                'stock' => 8,
                'status' => 'sale',
                'variant' => 'appliances',
                'isFeatured' => true,
                'brand_id' => $brandModels['lg']->id,
                'category_slug' => 'appliances',
                'images' => [
                    'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1588854337221-4cf9fa96059c?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'alpha 9 Gen7 AI Processor 4K with Brightness Booster, Dolby Vision & Atmos, 144Hz VRR with NVIDIA G-SYNC & AMD FreeSync Premium.',
                'description' => '<p>Bring cinema home with LG C4 OLED evo. Self-lit pixels deliver perfect black, 100% color fidelity, and lightning 0.1ms response times for next-level home entertainment.</p>',
            ],
            [
                '_id' => 'prod-14',
                'name' => 'Philips Hue Smart Home Ambient Bridge & Starter Kit',
                'slug' => 'philips-hue-smart-home-ambient-starter-kit',
                'price' => 199.99,
                'discount' => 15,
                'stock' => 22,
                'status' => 'new',
                'variant' => 'gadget',
                'isFeatured' => false,
                'brand_id' => $brandModels['google']->id,
                'category_slug' => 'smart-home-security',
                'images' => [
                    'https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1507499739999-097706ad8914?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => '16 million colors with sync to music and movies, Matter & Thread certified hub, automated sunrise/sunset circadian schedules.',
                'description' => '<p>Transform the atmosphere of your living spaces with dynamic multi-color smart lighting. Easy to control via voice assistant or mobile automation.</p>',
            ],
            [
                '_id' => 'prod-15',
                'name' => 'Apple AirPods Max Wireless Over-Ear Headphones Space Gray',
                'slug' => 'airpods-max-space-gray',
                'price' => 549.00,
                'discount' => 10,
                'stock' => 15,
                'status' => 'hot',
                'variant' => 'gadget',
                'isFeatured' => true,
                'brand_id' => $brandModels['apple']->id,
                'category_slug' => 'gadget-accessories',
                'images' => [
                    'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'Apple-designed dynamic driver, Active Noise Cancellation with Transparency mode, Personalized Spatial Audio with dynamic head tracking, knit-mesh canopy and memory foam ear cushions.',
                'description' => '<p>AirPods Max reimagine over-ear headphones. An Apple-designed driver provides high-fidelity audio. Every detail, from canopy to cushions, has been designed for an exceptional acoustic fit.</p>',
            ],
            [
                '_id' => 'prod-16',
                'name' => 'Dyson Purifier Hot+Cool Gen1 Smart Air Purifier & Heater',
                'slug' => 'dyson-purifier-hot-cool',
                'price' => 649.00,
                'discount' => 15,
                'stock' => 10,
                'status' => 'hot',
                'variant' => 'appliances',
                'isFeatured' => true,
                'brand_id' => $brandModels['lg']->id,
                'category_slug' => 'appliances',
                'images' => [
                    'https://images.unsplash.com/photo-1588854337221-4cf9fa96059c?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'Automatically senses and captures 99.97% of microscopic particles. HEPA H13 filtration with Air Multiplier technology to heat or cool the whole room.',
                'description' => '<p>Purifies and heats or cools the whole room. Fully sealed to HEPA H13 standard, capturing dust, allergens, and viruses while circulating purified air.</p>',
            ],
            [
                '_id' => 'prod-17',
                'name' => 'NVIDIA GeForce RTX 4090 Founders Edition 24GB',
                'slug' => 'nvidia-geforce-rtx-4090-founders-edition',
                'price' => 1599.99,
                'discount' => 5,
                'stock' => 6,
                'status' => 'hot',
                'variant' => 'gadget',
                'isFeatured' => true,
                'brand_id' => $brandModels['asus-rog']->id,
                'category_slug' => 'pc-components',
                'images' => [
                    'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'Ada Lovelace architecture, 24GB G6X memory, DLSS 3.5 AI neural rendering, 3rd gen RT cores for extreme 4K ray-traced gaming.',
                'description' => '<p>The ultimate GeForce GPU delivering an enormous leap in performance, efficiency, and AI-powered graphics.</p>',
            ],
            [
                '_id' => 'prod-18',
                'name' => 'ASUS ROG Maximus Z790 Dark Hero Flagship Motherboard',
                'slug' => 'asus-rog-maximus-z790-dark-hero',
                'price' => 699.99,
                'discount' => 10,
                'stock' => 14,
                'status' => 'new',
                'variant' => 'gadget',
                'isFeatured' => false,
                'brand_id' => $brandModels['asus-rog']->id,
                'category_slug' => 'pc-components',
                'images' => [
                    'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => '20+1+2 power stages, DDR5 with AEMP II, PCIe 5.0 M.2 slot, onboard Wi-Fi 7 with ASUS WiFi Q-Antenna, dual Thunderbolt 4 ports.',
                'description' => '<p>Engineered for extreme performance and effortless overclocking with unyielding power delivery and stealthy aesthetics.</p>',
            ],
            [
                '_id' => 'prod-19',
                'name' => 'Marshall Stanmore III Wireless Bluetooth Home Speaker',
                'slug' => 'marshall-stanmore-iii-bluetooth-speaker',
                'price' => 379.99,
                'discount' => 10,
                'stock' => 20,
                'status' => 'hot',
                'variant' => 'gadget',
                'isFeatured' => true,
                'brand_id' => $brandModels['marshall']->id,
                'category_slug' => 'audio-speakers',
                'images' => [
                    'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'Re-engineered for wider soundstage, Placement Compensation, Bluetooth 5.2 with LE Audio readiness, iconic Marshall vintage brass accents.',
                'description' => '<p>The heavy-weight speaker of the home lineup, Stanmore III brings expansive Marshall sound to any room in your home.</p>',
            ],
            [
                '_id' => 'prod-20',
                'name' => 'Bose Smart Ultra Soundbar with Dolby Atmos & Voice Control',
                'slug' => 'bose-smart-ultra-soundbar-dolby-atmos',
                'price' => 899.00,
                'discount' => 12,
                'stock' => 9,
                'status' => 'new',
                'variant' => 'appliances',
                'isFeatured' => true,
                'brand_id' => $brandModels['bose']->id,
                'category_slug' => 'audio-speakers',
                'images' => [
                    'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'Dolby Atmos and TrueSpace technology separate instruments, dialogue, and effects, placing them in distinct parts of a room for immersive cinema sound.',
                'description' => '<p>Experience top-of-the-line spatial immersion with Bose TrueSpace processing and upward firing dipole transducers.</p>',
            ],
            [
                '_id' => 'prod-21',
                'name' => 'Sony HT-A7000 7.1.2ch Flagship Dolby Atmos Soundbar',
                'slug' => 'sony-ht-a7000-dolby-atmos-soundbar',
                'price' => 1199.99,
                'discount' => 15,
                'stock' => 8,
                'status' => 'sale',
                'variant' => 'appliances',
                'isFeatured' => true,
                'brand_id' => $brandModels['sony']->id,
                'category_slug' => 'audio-speakers',
                'images' => [
                    'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => '360 Spatial Sound Mapping, Sound Field Optimization, 8K HDR/4K 120 passthrough, Hi-Res Audio, and integrated dual subwoofers.',
                'description' => '<p>Discover a whole new level of immersion that envelops you in surround sound with physical upward-firing and beam tweeters.</p>',
            ],
            [
                '_id' => 'prod-22',
                'name' => 'Theragun PRO Plus 6-in-1 Smart Percussive Therapy Massager',
                'slug' => 'theragun-pro-plus-smart-percussive-massager',
                'price' => 599.00,
                'discount' => 8,
                'stock' => 16,
                'status' => 'hot',
                'variant' => 'gadget',
                'isFeatured' => true,
                'brand_id' => $brandModels['apple']->id,
                'category_slug' => 'smart-health',
                'images' => [
                    'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'Near-infrared LED light therapy, vibration therapy, heat therapy, breathwork haptics, and 16mm deep percussive muscle relief.',
                'description' => '<p>The ultimate multi-therapy wellness device trusted by pro athletes for rapid recovery, pain relief, and performance enhancement.</p>',
            ],
            [
                '_id' => 'prod-23',
                'name' => 'Withings Body Scan Cellular Smart Composition Clinical Scale',
                'slug' => 'withings-body-scan-smart-composition-scale',
                'price' => 399.95,
                'discount' => 5,
                'stock' => 22,
                'status' => 'new',
                'variant' => 'gadget',
                'isFeatured' => false,
                'brand_id' => $brandModels['google']->id,
                'category_slug' => 'smart-health',
                'images' => [
                    'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'Segmental body composition (torso, arms, legs), 6-lead ECG recording, vascular age biomarker, and nerve health tracking with retractable handle.',
                'description' => '<p>A complete connected health station in your home. Provides in-depth segmental body fat and cardiovascular assessments.</p>',
            ],
            [
                '_id' => 'prod-24',
                'name' => 'ASUS ROG Rapture GT-BE98 Pro Quad-Band WiFi 7 Gaming Router',
                'slug' => 'asus-rog-rapture-gt-be98-pro-wifi-7-router',
                'price' => 799.99,
                'discount' => 10,
                'stock' => 11,
                'status' => 'hot',
                'variant' => 'gadget',
                'isFeatured' => true,
                'brand_id' => $brandModels['asus-rog']->id,
                'category_slug' => 'networking-wifi',
                'images' => [
                    'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'Quad-band speeds up to 30,000 Mbps, 320MHz channels, dual 10G ports, four 2.5G ports, Multi-Link Operation (MLO), and Triple-level game acceleration.',
                'description' => '<p>Unleash future-proof wireless performance for 8K streaming, cloud computing, and ultra-low latency esports competitive gaming.</p>',
            ],
            [
                '_id' => 'prod-25',
                'name' => 'Google Nest Wifi Pro 6E Mesh System 3-Pack Snow',
                'slug' => 'google-nest-wifi-pro-mesh-system',
                'price' => 399.99,
                'discount' => 15,
                'stock' => 25,
                'status' => 'sale',
                'variant' => 'gadget',
                'isFeatured' => false,
                'brand_id' => $brandModels['google']->id,
                'category_slug' => 'networking-wifi',
                'images' => [
                    'https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'Covers up to 6,600 sq ft, Tri-band Wi-Fi 6E with 6GHz band, built-in Matter and Thread border router, intelligent auto-monitoring self-healing network.',
                'description' => '<p>Fast, reliable, and whole-home coverage. Built to support up to 300 connected smart home devices without slowdown.</p>',
            ],
            [
                '_id' => 'prod-26',
                'name' => 'Anker Prime 27,650mAh Power Bank 250W GaN Fast Charger',
                'slug' => 'anker-prime-27650mah-power-bank-250w',
                'price' => 179.99,
                'discount' => 10,
                'stock' => 30,
                'status' => 'hot',
                'variant' => 'gadget',
                'isFeatured' => false,
                'brand_id' => $brandModels['logitech']->id,
                'category_slug' => 'power-charging',
                'images' => [
                    'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => '250W multi-device fast output, 27,650mAh airline-approved capacity, smart digital display with app Bluetooth monitoring, dual USB-C PD 3.1.',
                'description' => '<p>Charge MacBook Pro 16" to 50% in just 28 minutes while simultaneously fast charging phones and accessories on the go.</p>',
            ],
            [
                '_id' => 'prod-27',
                'name' => 'EcoFlow RIVER 2 Pro 768Wh Portable Solar Generator Station',
                'slug' => 'ecoflow-river-2-pro-portable-power-station',
                'price' => 599.00,
                'discount' => 18,
                'stock' => 12,
                'status' => 'sale',
                'variant' => 'appliances',
                'isFeatured' => true,
                'brand_id' => $brandModels['lg']->id,
                'category_slug' => 'power-charging',
                'images' => [
                    '/storage/products/ecoflow_river2_pro.webp',
                    'https://images.unsplash.com/photo-1592833159155-c62df1b65634?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'LiFePO4 battery chemistry with 3000+ cycles, 70-minute ultra-fast AC recharge, 800W output with X-Boost up to 1600W, app control via Wi-Fi/Bluetooth.',
                'description' => '<p>Power 80% of your essential home appliances during blackouts, outdoor excursions, and remote workstation setups.</p>',
            ],
            [
                '_id' => 'prod-28',
                'name' => 'Samsung Galaxy Tab S10 Ultra 14.6" Dynamic AMOLED 2X 512GB',
                'slug' => 'samsung-galaxy-tab-s10-ultra',
                'price' => 1199.99,
                'discount' => 10,
                'stock' => 15,
                'status' => 'hot',
                'variant' => 'tablets',
                'isFeatured' => true,
                'brand_id' => $brandModels['samsung']->id,
                'category_slug' => 'tablets-ereaders',
                'images' => [
                    'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => '14.6-inch anti-reflective Dynamic AMOLED 2X, MediaTek Dimensity 9300+ 4nm flagship processor, Galaxy AI S-Pen with Air Commands, IP68 water resistance.',
                'description' => '<p>Expansive display, pro multitasking, and AI-assisted creativity for designers, creators, and power users.</p>',
            ],
            [
                '_id' => 'prod-29',
                'name' => 'Microsoft Surface Pro 11 Copilot+ PC OLED 2-in-1 Tablet',
                'slug' => 'microsoft-surface-pro-11-copilot-pc',
                'price' => 1499.99,
                'discount' => 8,
                'stock' => 18,
                'status' => 'new',
                'variant' => 'tablets',
                'isFeatured' => true,
                'brand_id' => $brandModels['microsoft']->id,
                'category_slug' => 'tablets-ereaders',
                'images' => [
                    'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'Snapdragon X Elite processor with 45 TOPS NPU, vibrant OLED HDR touchscreen, all-day battery life, Wi-Fi 7, and Surface Slim Pen haptic integration.',
                'description' => '<p>The most flexible and powerful 2-in-1 ever, infused with Copilot+ AI experiences and premium anodized aluminum chassis.</p>',
            ],
            [
                '_id' => 'prod-30',
                'name' => 'Razer Blade 16 Dual-Mode Mini-LED Gaming Laptop',
                'slug' => 'razer-blade-16-gaming-laptop',
                'price' => 3299.99,
                'discount' => 12,
                'stock' => 8,
                'status' => 'hot',
                'variant' => 'laptops',
                'isFeatured' => true,
                'brand_id' => $brandModels['razer']->id,
                'category_slug' => 'gaming',
                'images' => [
                    'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'Dual-mode Mini-LED display (UHD+ 120Hz & FHD+ 240Hz), Intel Core i9-14900HX, NVIDIA GeForce RTX 4090 16GB VRAM, patented vapor chamber cooling.',
                'description' => '<p>Experience insane visual clarity and depth of color with the world\'s first dual-mode Mini-LED display backed by desktop-class gaming muscle.</p>',
            ],
            [
                '_id' => 'prod-31',
                'name' => 'Razer Huntsman V3 Pro Analog Optical Gaming Keyboard',
                'slug' => 'razer-huntsman-v3-pro-analog-keyboard',
                'price' => 249.99,
                'discount' => 10,
                'stock' => 24,
                'status' => 'new',
                'variant' => 'gadget',
                'isFeatured' => false,
                'brand_id' => $brandModels['razer']->id,
                'category_slug' => 'gaming',
                'images' => [
                    'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => '2nd-Gen Analog Optical Switches with Rapid Trigger mode, adjustable actuation from 0.1mm to 4.0mm, multi-function digital dial with 3 dedicated macro buttons.',
                'description' => '<p>Engineered for esports perfection with ultra-responsive rapid trigger actuation and textured doubleshot PBT keycaps.</p>',
            ],
            [
                '_id' => 'prod-32',
                'name' => 'Sony PlayStation 5 Pro 2TB Digital Gaming Console',
                'slug' => 'sony-playstation-5-pro-console',
                'price' => 699.99,
                'discount' => 0,
                'stock' => 12,
                'status' => 'hot',
                'variant' => 'gadget',
                'isFeatured' => true,
                'brand_id' => $brandModels['sony']->id,
                'category_slug' => 'gaming',
                'images' => [
                    'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'PlayStation Spectral Super Resolution (PSSR) AI upscaling, 67% more Compute Units, advanced hardware ray tracing, and 2TB high-speed NVMe storage.',
                'description' => '<p>Play your favorite games at constant 60fps with maximum fidelity ray-tracing and next-gen DualSense haptic feedback.</p>',
            ],
            [
                '_id' => 'prod-33',
                'name' => 'Sony PlayStation VR2 Headset Horizon Call of the Mountain Bundle',
                'slug' => 'sony-playstation-vr2-horizon-bundle',
                'price' => 549.99,
                'discount' => 15,
                'stock' => 10,
                'status' => 'sale',
                'variant' => 'gadget',
                'isFeatured' => false,
                'brand_id' => $brandModels['sony']->id,
                'category_slug' => 'gaming',
                'images' => [
                    'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => '4K HDR OLED displays (2000 x 2040 per eye), 110-degree field of view, intelligent eye tracking with foveated rendering, headset feedback vibrations.',
                'description' => '<p>Escape into worlds that feel, look and sound truly real with cutting-edge virtual reality technology and sensory features.</p>',
            ],
            [
                '_id' => 'prod-34',
                'name' => 'Microsoft Surface Laptop 7 15" PixelSense Copilot+ PC',
                'slug' => 'microsoft-surface-laptop-7-copilot-pc',
                'price' => 1399.00,
                'discount' => 8,
                'stock' => 14,
                'status' => 'new',
                'variant' => 'laptops',
                'isFeatured' => true,
                'brand_id' => $brandModels['microsoft']->id,
                'category_slug' => 'laptops',
                'images' => [
                    'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'Snapdragon X Elite 12-core silicon, ultra-thin bezels with 120Hz PixelSense Flow touchscreen, up to 22 hours of battery life, Studio Camera with AI effects.',
                'description' => '<p>A masterpiece of productivity featuring industry-leading performance per watt and intuitive generative AI tools.</p>',
            ],
            [
                '_id' => 'prod-35',
                'name' => 'Apple MacBook Air 15-inch M3 Midnight 512GB',
                'slug' => 'apple-macbook-air-15-inch-m3',
                'price' => 1499.00,
                'discount' => 7,
                'stock' => 19,
                'status' => 'hot',
                'variant' => 'laptops',
                'isFeatured' => false,
                'brand_id' => $brandModels['apple']->id,
                'category_slug' => 'laptops',
                'images' => [
                    'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'Apple M3 chip with 8-core CPU and 10-core GPU, fanless whisper-quiet design, 15.3-inch Liquid Retina display, support for two external monitors.',
                'description' => '<p>Impossibly thin and fast. MacBook Air with M3 makes working and playing across massive displays effortless and silent.</p>',
            ],
            [
                '_id' => 'prod-36',
                'name' => 'Samsung Galaxy Z Fold6 512GB Silver Shadow',
                'slug' => 'samsung-galaxy-z-fold6-ai-smartphone',
                'price' => 1899.99,
                'discount' => 10,
                'stock' => 13,
                'status' => 'hot',
                'variant' => 'smartphones',
                'isFeatured' => true,
                'brand_id' => $brandModels['samsung']->id,
                'category_slug' => 'smartphones',
                'images' => [
                    'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'Enhanced dual-rail Armor Aluminum hinge, 7.6-inch Dynamic AMOLED 2X 2600 nits inner screen, Note Assist and Circle to Search with Google AI.',
                'description' => '<p>Sleeker, lighter, and more durable than ever before. Unfold PC-style productivity right inside your palm.</p>',
            ],
            [
                '_id' => 'prod-37',
                'name' => 'Google Pixel 9 Pro 256GB Hazel Tensor G4',
                'slug' => 'google-pixel-9-pro-hazel-256gb',
                'price' => 999.00,
                'discount' => 5,
                'stock' => 20,
                'status' => 'new',
                'variant' => 'smartphones',
                'isFeatured' => false,
                'brand_id' => $brandModels['google']->id,
                'category_slug' => 'smartphones',
                'images' => [
                    'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'Google Tensor G4, 16GB RAM for on-device Gemini, pro triple rear camera with 5x optical telephoto and 30x Super Res Zoom, 7 years of OS updates.',
                'description' => '<p>The most powerful Pixel yet with a refined satin glass back, polished metal frame, and pro camera controls.</p>',
            ],
            [
                '_id' => 'prod-38',
                'name' => 'Samsung Galaxy Watch Ultra 47mm LTE Titanium Gray',
                'slug' => 'samsung-galaxy-watch-ultra-titanium',
                'price' => 649.99,
                'discount' => 12,
                'stock' => 14,
                'status' => 'hot',
                'variant' => 'smart-watches',
                'isFeatured' => true,
                'brand_id' => $brandModels['samsung']->id,
                'category_slug' => 'smart-watches',
                'images' => [
                    'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'Cushion titanium design with 10ATM & IP68 water resistance, Dual-frequency GPS, Energy Score with Galaxy AI, up to 100 hours power-saving battery.',
                'description' => '<p>Engineered for extreme performance and outdoor expeditions with ocean-grade water resistance and emergency siren.</p>',
            ],
            [
                '_id' => 'prod-39',
                'name' => 'Google Pixel Watch 3 45mm Actua Display Matte Black',
                'slug' => 'google-pixel-watch-3-45mm-matte-black',
                'price' => 399.99,
                'discount' => 0,
                'stock' => 17,
                'status' => 'new',
                'variant' => 'smart-watches',
                'isFeatured' => false,
                'brand_id' => $brandModels['google']->id,
                'category_slug' => 'smart-watches',
                'images' => [
                    'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'Larger 45mm Actua display with 2000 nits peak brightness, custom running workouts, Loss of Pulse Detection, 24-hour battery with fast charge.',
                'description' => '<p>Combines Fitbit\'s best health tracking with Google\'s helpfulness and stunning domed glass aesthetic.</p>',
            ],
            [
                '_id' => 'prod-40',
                'name' => 'Marshall Major V Wireless Bluetooth Headphones',
                'slug' => 'marshall-major-v-wireless-headphones',
                'price' => 149.99,
                'discount' => 10,
                'stock' => 28,
                'status' => 'hot',
                'variant' => 'gadget',
                'isFeatured' => true,
                'brand_id' => $brandModels['marshall']->id,
                'category_slug' => 'gadget-accessories',
                'images' => [
                    'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => '100+ hours of wireless playtime, rugged foldable vintage design, custom-tuned dynamic drivers, customizable M-button for Spotify Tap.',
                'description' => '<p>Classic rock heritage packed into modern wireless cans that play for over four days straight without touching a charger.</p>',
            ],
            [
                '_id' => 'prod-41',
                'name' => 'Sony WF-1000XM5 True Wireless Noise Canceling Earbuds',
                'slug' => 'sony-wf-1000xm5-wireless-earbuds',
                'price' => 299.99,
                'discount' => 15,
                'stock' => 22,
                'status' => 'sale',
                'variant' => 'gadget',
                'isFeatured' => false,
                'brand_id' => $brandModels['sony']->id,
                'category_slug' => 'gadget-accessories',
                'images' => [
                    'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => 'Integrated Processor V2 and HD Noise Canceling Processor QN2e, Dynamic Driver X for wide frequency reproduction, bone conduction voice sensors.',
                'description' => '<p>Astonishing sound quality and the best noise cancellation performance on the market in an ultra-compact earbud footprint.</p>',
            ],
            [
                '_id' => 'prod-42',
                'name' => 'DJI Osmo Pocket 3 4K 120fps Handheld Gimbal Camera Creator Combo',
                'slug' => 'dji-osmo-pocket-3-creator-combo',
                'price' => 669.00,
                'discount' => 5,
                'stock' => 11,
                'status' => 'hot',
                'variant' => 'cameras',
                'isFeatured' => true,
                'brand_id' => $brandModels['dji']->id,
                'category_slug' => 'cameras-drones',
                'images' => [
                    'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => '1-inch CMOS sensor, 4K/120fps recording, 2-inch rotatable OLED screen with smart horizontal-vertical switching, 3-axis mechanical gimbal stabilization.',
                'description' => '<p>Puts powerful imaging in the palm of your hand for vloggers, creators, and filmmakers on the move.</p>',
            ],
            [
                '_id' => 'prod-43',
                'name' => 'Sony Alpha 7R V Full-Frame High-Resolution Camera Body',
                'slug' => 'sony-alpha-7r-v-mirrorless-camera',
                'price' => 3899.99,
                'discount' => 8,
                'stock' => 5,
                'status' => 'new',
                'variant' => 'cameras',
                'isFeatured' => true,
                'brand_id' => $brandModels['sony']->id,
                'category_slug' => 'cameras-drones',
                'images' => [
                    'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80',
                    'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => '61.0MP full-frame Exmor R BSI CMOS sensor, dedicated AI Processing Unit for Real-time Recognition AF, 8-stop in-body 5-axis image stabilization.',
                'description' => '<p>Combines a 61MP sensor with an unprecedented AI processing unit for next-generation subject recognition and extreme resolution capture.</p>',
            ],
            [
                '_id' => 'prod-44',
                'name' => 'Samsung Odyssey OLED G9 49" Curved Dual QHD 240Hz Gaming Monitor',
                'slug' => 'samsung-odyssey-oled-g9-49-inch-curved',
                'price' => 1499.99,
                'discount' => 18,
                'stock' => 7,
                'status' => 'sale',
                'variant' => 'monitors',
                'isFeatured' => true,
                'brand_id' => $brandModels['samsung']->id,
                'category_slug' => 'monitors-displays',
                'images' => [
                    'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => '49-inch 1800R curved OLED display, Dual QHD (5120 x 1440), 0.03ms response time, 240Hz refresh rate, Neo Quantum Processor Pro.',
                'description' => '<p>Immerse your senses in a wrap-around panoramic battlefield with hair-raising response times and inky blacks.</p>',
            ],
            [
                '_id' => 'prod-45',
                'name' => 'LG UltraFine 32" Ergo 4K UHD IPS Display with USB-C',
                'slug' => 'lg-ultrafine-32-inch-ergo-4k-uhd-monitor',
                'price' => 649.99,
                'discount' => 12,
                'stock' => 16,
                'status' => 'new',
                'variant' => 'monitors',
                'isFeatured' => false,
                'brand_id' => $brandModels['lg']->id,
                'category_slug' => 'monitors-displays',
                'images' => [
                    'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => '31.5-inch 4K UHD (3840 x 2160) IPS, DCI-P3 95%, HDR10, innovative Ergo Stand with extend/retract/swivel/pivot/height/tilt adjust, USB-C 60W PD.',
                'description' => '<p>Designed to transform your workspace ergonomics while rendering razor-sharp 4K color accurate imagery for professionals.</p>',
            ],
            [
                '_id' => 'prod-46',
                'name' => 'Google Nest Learning Thermostat 4th Gen Polished Obsidian',
                'slug' => 'google-nest-learning-thermostat-4th-gen',
                'price' => 279.99,
                'discount' => 10,
                'stock' => 24,
                'status' => 'hot',
                'variant' => 'appliances',
                'isFeatured' => true,
                'brand_id' => $brandModels['google']->id,
                'category_slug' => 'smart-home-security',
                'images' => [
                    'https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80',
                ],
                'keyfeature' => '60% larger borderless domed glass display, Dynamic Farsight, Smart Schedule with Google Home AI, Matter enabled, saves an average of 15% on heating and cooling.',
                'description' => '<p>The iconic smart thermostat, re-imagined with a breathtaking borderless design and machine learning that learns your comfort habits.</p>',
            ],
        ];

        foreach ($products as $pData) {
            $categorySlug = $pData['category_slug'];
            unset($pData['category_slug']);

            $product = Product::updateOrCreate(
                ['slug' => $pData['slug']],
                $pData
            );

            if (isset($categoryModels[$categorySlug])) {
                $product->categories()->sync([$categoryModels[$categorySlug]->id]);
            }
        }

        // 6. Authors and Blogs
        $author = Author::updateOrCreate(
            ['slug' => 'alex-rivera'],
            [
                '_id' => 'author-1',
                'name' => 'Alex Rivera',
                'slug' => 'alex-rivera',
                'image' => 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
                'bio' => 'Senior tech columnist and audio engineer covering consumer computing.',
            ]
        );

        $blogCategory = BlogCategory::updateOrCreate(
            ['slug' => 'audio-tech'],
            ['_id' => 'bcat-1', 'title' => 'Audio & Gadgets', 'slug' => 'audio-tech']
        );

        $blog = Blog::updateOrCreate(
            ['slug' => 'spatial-audio-breakthrough-2026'],
            [
                '_id' => 'blog-1',
                'title' => 'The Spatial Audio Revolution: How Computation Transforms Listening',
                'slug' => 'spatial-audio-breakthrough-2026',
                'mainImage' => 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=1200&auto=format&fit=crop&q=80',
                'publishedAt' => now()->subDays(2),
                'author_id' => $author->id,
                'body' => [
                    'Spatial audio is transforming how we experience music and games. By leveraging dynamic head tracking and binaural rendering, soundscapes feel physical and expansive.',
                ],
            ]
        );
        $blog->blogcategories()->sync([$blogCategory->id]);

        // 7. Addresses
        Address::updateOrCreate(
            ['name' => 'Default Shipping Address'],
            [
                '_id' => 'addr-1',
                'user_id' => (string) $user->id,
                'name' => 'Default Shipping Address',
                'email' => 'test@example.com',
                'address' => 'House 12, Road 4, Sector 7',
                'city' => 'Dhaka',
                'District' => 'Dhaka',
                'zip' => '1230',
                'phone' => '+8801700000000',
                'default' => true,
            ]
        );
    }
}
